/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Box: typeof import('./src/components/box.vue')['default']
    Choices: typeof import('./src/components/choices.vue')['default']
    ChoicesBtn: typeof import('./src/components/choicesBtn.vue')['default']
    copy: typeof import('./src/components/options copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    New: typeof import('./src/components/new.vue')['default']
    Old: typeof import('./src/components/old.vue')['default']
    Options: typeof import('./src/components/options.vue')['default']
    OptionsBtn: typeof import('./src/components/optionsBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalekAvatar: typeof import('./src/components/salekAvatar.vue')['default']
    WhiteBox: typeof import('./src/components/whiteBox.vue')['default']

    Desktop: typeof import('./src/layout/desktop/index.vue')['default']
    Mobile: typeof import('./src/layout/mobile/index.vue')['default']
  }
}
