/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Box: typeof import('./src/components/box.vue')['default']
    Choices: typeof import('./src/components/choices.vue')['default']
    ChoicesBtn: typeof import('./src/components/choicesBtn.vue')['default']
    Options: typeof import('./src/components/options.vue')['default']
    OptionsBtn: typeof import('./src/components/optionsBtn.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    ProgressBox: typeof import('./src/components/ProgressBox.vue')['default']
    ProgressFill: typeof import('./src/components/ProgressFill.vue')['default']
    SalekAvatar: typeof import('./src/components/salekAvatar.vue')['default']
  }
}
